export const mockRestaurants = [
  {
    id: "1",
    name: "Bún bò Huế",
    slug: "bun-bo-hue",
    description: "Bún bò Huế cho bữa trưa gần 219 Trung Kính",
    address: "Gần 219 Trung Kính, Cầu Giấy, Hà Nội",
    imageUrl: "/restaurants/img-8824.jpg",
    tags: ["bun", "nong", "trua"],
    avgRating: 4.5,
    reviewCount: 10,
  },
  {
    id: "2",
    name: "Bún cá cay Hải Phòng",
    slug: "bun-ca-cay-hai-phong",
    description: "Bún cá cay Hải Phòng quanh Trung Kính",
    address: "Gần 219 Trung Kính, Cầu Giấy, Hà Nội",
    imageUrl: "/restaurants/img-8825.jpg",
    tags: ["bun", "nong", "cay", "trua"],
    avgRating: 4.2,
    reviewCount: 8,
  },
  {
    id: "3",
    name: "Cơm tấm sườn bì",
    slug: "com-tam-suon-bi",
    description: "Cơm tấm sườn bì truyền thống",
    address: "Gần 219 Trung Kính, Cầu Giấy, Hà Nội",
    imageUrl: "/restaurants/img-8824.jpg",
    tags: ["com", "trua"],
    avgRating: 4.8,
    reviewCount: 15,
  },
];
